#!/bin/bash

# Check if a folder path is provided
if [ "$#" -eq 0 ]; then
    folder_path="."
elif [ "$#" -eq 1 ]; then
    folder_path="$1"
else
    echo "Usage: $0 [folder_path]"
    exit 1
fi

# Call the Python script with the determined folder path
python "$(dirname "$0")/sanitize_filenames_in_folder.py" "$folder_path"
